//! The C header is checked against the Rust struct by a C compiler.
//!
//! `include/partitions.h` is a hand-written transcription of the
//! `#[repr(C)]` structs in `src/capi.rs`. Nothing in the Rust test suite can
//! see a mistake in that transcription, because every Rust test builds
//! `PartitionInfo` from the Rust side. The failure mode is silent and it is
//! in the caller's address space: `partitions_get` writes a whole struct
//! through `out`, so a header short by one field means the callee scribbles
//! past the end of a C caller's stack slot.
//!
//! So this test hands the question to the only tool that can answer it. It
//! writes a C file that includes the shipped header and `_Static_assert`s
//! `sizeof` and every `offsetof` against the numbers Rust reports for the
//! same struct at runtime, then compiles it. Drift on either side — a field
//! added to the Rust struct, a field missed in the header, a type changed in
//! one and not the other — is a compile error naming the field.

use std::fs;
use std::mem::{align_of, offset_of, size_of};
use std::path::Path;
use std::process::Command;

use partitions::capi::PartitionInfo;

/// `include/partitions.h` opens with `#include "fs_core.h"`, which lives in
/// the sibling `am-fs-core` crate. Use the real one when the sibling is
/// checked out beside us (it is, both locally and in CI, because Cargo
/// resolves the path dependency from there); otherwise fall back to a
/// declaration-only stand-in, since nothing in `PartitionInfo` is an
/// `fs_core` type and the layout question does not depend on it.
const FS_CORE_STUB: &str = r#"
#ifndef FS_CORE_H_STANDIN
#define FS_CORE_H_STANDIN
#include <stdint.h>
#include <stddef.h>
typedef int32_t FsCoreErrorCode;
typedef struct FsCoreDevice FsCoreDevice;
#endif
"#;

/// Every field of `PartitionInfo`, paired with the offset Rust gives it.
/// The names are spelled the way the C header spells them.
fn partition_info_layout() -> Vec<(&'static str, usize)> {
    vec![
        ("start", offset_of!(PartitionInfo, start)),
        ("length", offset_of!(PartitionInfo, length)),
        ("fs_kind", offset_of!(PartitionInfo, fs_kind)),
        ("table_kind", offset_of!(PartitionInfo, table_kind)),
        ("type_guid", offset_of!(PartitionInfo, type_guid)),
        ("type_byte", offset_of!(PartitionInfo, type_byte)),
        ("_pad", offset_of!(PartitionInfo, _pad)),
        ("label", offset_of!(PartitionInfo, label)),
        ("label_len", offset_of!(PartitionInfo, label_len)),
        ("bootable", offset_of!(PartitionInfo, bootable)),
        ("_pad2", offset_of!(PartitionInfo, _pad2)),
        ("attributes", offset_of!(PartitionInfo, attributes)),
    ]
}

fn generate_assertions() -> String {
    let mut c = String::from(
        "/* Generated by tests/c_abi.rs. Every number below came from Rust. */\n\
         #include <stddef.h>\n\
         #include \"partitions.h\"\n\n",
    );
    c.push_str(&format!(
        "_Static_assert(sizeof(PartitionInfo) == {}, \
         \"PartitionInfo is a different size in include/partitions.h than in src/capi.rs — \
         partitions_get overruns its caller's buffer\");\n",
        size_of::<PartitionInfo>()
    ));
    c.push_str(&format!(
        "_Static_assert(_Alignof(PartitionInfo) == {}, \
         \"PartitionInfo alignment differs between include/partitions.h and src/capi.rs\");\n",
        align_of::<PartitionInfo>()
    ));
    for (field, offset) in partition_info_layout() {
        c.push_str(&format!(
            "_Static_assert(offsetof(PartitionInfo, {field}) == {offset}, \
             \"PartitionInfo.{field} sits at a different offset in include/partitions.h \
             than in src/capi.rs\");\n"
        ));
    }
    c
}

/// First C compiler that answers `--version`. `CC` wins if it is set.
fn find_c_compiler() -> Option<String> {
    let answers = |cmd: &str| {
        Command::new(cmd)
            .arg("--version")
            .output()
            .map(|out| out.status.success())
            .unwrap_or(false)
    };
    if let Ok(cc) = std::env::var("CC") {
        if !cc.is_empty() && answers(&cc) {
            return Some(cc);
        }
    }
    ["cc", "clang", "gcc"]
        .into_iter()
        .find(|cmd| answers(cmd))
        .map(str::to_owned)
}

#[test]
fn c_header_matches_rust_struct() {
    let Some(cc) = find_c_compiler() else {
        // A developer without a C compiler should not get a red suite, but a
        // CI run that quietly skips this is a guard that has stopped
        // guarding. The Windows runner is exempt because a POSIX-named C
        // compiler is not a given there.
        assert!(
            std::env::var_os("CI").is_none() || cfg!(target_os = "windows"),
            "no C compiler found in CI — the C ABI header check would have been skipped"
        );
        eprintln!("no C compiler found (tried $CC, cc, clang, gcc); skipping C ABI check");
        return;
    };

    let dir = tempfile::tempdir().expect("temp dir");
    let include = dir.path();

    let header = Path::new("include/partitions.h");
    fs::copy(header, include.join("partitions.h")).expect("copy include/partitions.h");

    let sibling = Path::new("../rust-fs-core/include/fs_core.h");
    if sibling.exists() {
        fs::copy(sibling, include.join("fs_core.h")).expect("copy sibling fs_core.h");
    } else {
        fs::write(include.join("fs_core.h"), FS_CORE_STUB).expect("write fs_core.h stand-in");
    }

    let source = include.join("abi_check.c");
    fs::write(&source, generate_assertions()).expect("write abi_check.c");

    let output = Command::new(&cc)
        .arg("-std=c11")
        .arg("-c")
        .arg(&source)
        .arg("-I")
        .arg(include)
        .arg("-o")
        .arg(include.join("abi_check.o"))
        .output()
        .unwrap_or_else(|e| panic!("failed to run {cc}: {e}"));

    assert!(
        output.status.success(),
        "include/partitions.h disagrees with the Rust #[repr(C)] structs in src/capi.rs.\n\
         Compiler: {cc}\n\
         {}",
        String::from_utf8_lossy(&output.stderr)
    );
}
